add_newline = false

format = """
$hostname\
$username\
$directory\
$git_branch\
$git_state\
$git_metrics
$character
"""
# format = "$all"
# format = "$java"
# format = "$git_commit"

# scan_timeout = 30
# command_timeout = 500

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
style    = "bold fg:16 bg:196"
format   = "[ğŸ’» $hostname ]($style)"
trim_at  = ".local"

[username]
style_user  = "bold fg:16 bg:70"
format      = "[ğŸ‘¤ $user ]($style)"
show_always = true

[directory]
style             = "bold fg:16 bg:45"
format            = "[ğŸ“‚ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncation_symbol = "â€¦/"
truncate_to_repo  = false

[character]
success_symbol = "[ï„  ](bold green)"
error_symbol   = "[ï„  ](#ff0000)"

[fill]
symbol = " "

[time]
disabled    = true
format      = "[$time]($style) "
style       = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled  = true
format    = "use [$symbol$ram]($style) "
symbol    = "ï¡š "
style     = "dimmed"
threshold = 50

[status]
disabled = true

[python]
version_format = ""
symbol         = "ï Ÿ "
style          = "blold green"
[golang]
version_format = ""
symbol         = "ï³‘ "
[kotlin]
version_format = ""
kotlin_binary  = "kotlin"
[java]
version_format = ""
[php]
version_format = ""
symbol         = "î˜ˆ "

[shell]
disabled       = true
fish_indicator = "[ïœ¹](#3595ff)"

[git_branch]
style  = "bold fg:16 bg:183"
symbol = "î‚  "
format = "[$symbol$branch(:$remote_branch) ]($style)"
# always_show_remote = true
# format             = "on [$symbol$branch]($style) "
# symbol             = "ïˆ "
# style              = "fg:#b2d500"

[git_status]
format    = "([$all_status$ahead_behind ]($style))"
ahead     = "â‡¡${count}"
diverged  = "â‡•â‡¡${ahead_count},â‡£${behind_count}"
behind    = "â‡£${count}"
untracked = '\(ï™ $count\)'
modified  = '\(ï€ $count\)'
staged    = '\(ï§ $count\)'
renamed   = '\(Aï‰†$count\)'
deleted   = '\(ï«§$count\)'
stashed   = "ï€œ "
style     = "fg:#b2d500"

[git_commit]
commit_hash_length = 8
tag_symbol         = "ğŸ”– "
style              = "bold yellow"
