format = """
$hostname\
$username\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status
$character
"""
add_newline = false

scan_timeout    = 30
command_timeout = 100

[cmd_duration]
disabled = true

[hostname]
ssh_only = false
disabled = true
style    = "bold fg:17"
format   = "[ğŸ’» $hostname ]($style)"
trim_at  = ".local"

[username]
# style_user  = "bold fg:17"
# format      = "[ğŸ‘¤ $user ]($style)"
show_always = true

[directory]
# style             = "bold fg:17"
# format            = "[ğŸ“‚ $path ]($style)[$read_only]($read_only_style)"
# truncation_length = 2
# truncation_symbol = "â€¦/"
# truncate_to_repo  = false

[character]
success_symbol = "[ï„  ](green)"
error_symbol   = "[ï„  ](#ff0000)"

[fill]
symbol = " "

[time]
disabled    = true
format      = "[$time]($style) "
style       = "dimmed gray"
time_format = "%R"

[memory_usage]
disabled  = true
format    = "use [$symbol$ram]($style) "
symbol    = "ï¡š "
style     = "dimmed"
threshold = 50

[status]
disabled = true

[git_branch]
style  = "bold fg:16 bg:183"
symbol = "î‚  "
format = "[$symbol$branch(->origin/$remote_branch) ]($style)"

[git_status]
format    = "([$all_status$ahead_behind ]($style))"
ahead     = "â‡¡${count}"
diverged  = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind    = "â‡£$count"
untracked = 'ï™ $count '
modified  = 'ï€ $count '
staged    = 'ï§ $count '
renamed   = 'Aï‰†$count '
deleted   = 'ï«§$count '
stashed   = 'ï€œ $count '
style     = 'bold fg:16 bg:183'
